using System;


namespace So.Demo.Common.Entities
{
	public class Customer
	{
		        public string String1 { get; set; }
        public string String2 { get; set; }
        public string String3 { get; set; }
        public string String4 { get; set; }
        public string String5 { get; set; }
        public string String6 { get; set; }
        public string String7 { get; set; }
        public string String8 { get; set; }
        public string String9 { get; set; }
        public string String10 { get; set; }
        public string String11 { get; set; }
        public string String12 { get; set; }
        public string String13 { get; set; }
        public string String14 { get; set; }
        public string String15 { get; set; }
        public string String16 { get; set; }
        public string String17 { get; set; }
        public string String18 { get; set; }
        public string String19 { get; set; }
        public string String20 { get; set; }
        public int Int1 { get; set; }
        public int Int2 { get; set; }
        public int Int3 { get; set; }
        public int Int4 { get; set; }
        public int Int5 { get; set; }
        public int Int6 { get; set; }
        public int Int7 { get; set; }
        public int Int8 { get; set; }
        public int Int9 { get; set; }
        public int Int10 { get; set; }
        public int Int11 { get; set; }
        public int Int12 { get; set; }
        public int Int13 { get; set; }
        public int Int14 { get; set; }
        public int Int15 { get; set; }
        public int Int16 { get; set; }
        public int Int17 { get; set; }
        public int Int18 { get; set; }
        public int Int19 { get; set; }
        public int Int20 { get; set; }
        public DateTime DateTime1 { get; set; }
        public DateTime DateTime2 { get; set; }
        public DateTime DateTime3 { get; set; }
        public DateTime DateTime4 { get; set; }
        public DateTime DateTime5 { get; set; }
        public DateTime DateTime6 { get; set; }
        public DateTime DateTime7 { get; set; }
        public DateTime DateTime8 { get; set; }
        public DateTime DateTime9 { get; set; }
        public DateTime DateTime10 { get; set; }
        public DateTime DateTime11 { get; set; }
        public DateTime DateTime12 { get; set; }
        public DateTime DateTime13 { get; set; }
        public DateTime DateTime14 { get; set; }
        public DateTime DateTime15 { get; set; }
        public DateTime DateTime16 { get; set; }
        public DateTime DateTime17 { get; set; }
        public DateTime DateTime18 { get; set; }
        public DateTime DateTime19 { get; set; }
        public DateTime DateTime20 { get; set; }
        public Guid Guid1 { get; set; }
        public Guid Guid2 { get; set; }
        public Guid Guid3 { get; set; }
        public Guid Guid4 { get; set; }
        public Guid Guid5 { get; set; }
        public Guid Guid6 { get; set; }
        public Guid Guid7 { get; set; }
        public Guid Guid8 { get; set; }
        public Guid Guid9 { get; set; }
        public Guid Guid10 { get; set; }
        public Guid Guid11 { get; set; }
        public Guid Guid12 { get; set; }
        public Guid Guid13 { get; set; }
        public Guid Guid14 { get; set; }
        public Guid Guid15 { get; set; }
        public Guid Guid16 { get; set; }
        public Guid Guid17 { get; set; }
        public Guid Guid18 { get; set; }
        public Guid Guid19 { get; set; }
        public Guid Guid20 { get; set; }
        public double Double1 { get; set; }
        public double Double2 { get; set; }
        public double Double3 { get; set; }
        public double Double4 { get; set; }
        public double Double5 { get; set; }
        public double Double6 { get; set; }
        public double Double7 { get; set; }
        public double Double8 { get; set; }
        public double Double9 { get; set; }
        public double Double10 { get; set; }
        public double Double11 { get; set; }
        public double Double12 { get; set; }
        public double Double13 { get; set; }
        public double Double14 { get; set; }
        public double Double15 { get; set; }
        public double Double16 { get; set; }
        public double Double17 { get; set; }
        public double Double18 { get; set; }
        public double Double19 { get; set; }
        public double Double20 { get; set; }
        public decimal Decimal1 { get; set; }
        public decimal Decimal2 { get; set; }
        public decimal Decimal3 { get; set; }
        public decimal Decimal4 { get; set; }
        public decimal Decimal5 { get; set; }
        public decimal Decimal6 { get; set; }
        public decimal Decimal7 { get; set; }
        public decimal Decimal8 { get; set; }
        public decimal Decimal9 { get; set; }
        public decimal Decimal10 { get; set; }
        public decimal Decimal11 { get; set; }
        public decimal Decimal12 { get; set; }
        public decimal Decimal13 { get; set; }
        public decimal Decimal14 { get; set; }
        public decimal Decimal15 { get; set; }
        public decimal Decimal16 { get; set; }
        public decimal Decimal17 { get; set; }
        public decimal Decimal18 { get; set; }
        public decimal Decimal19 { get; set; }
        public decimal Decimal20 { get; set; }
	}
}